server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_signal
    username: ${LOCAL_USERNAME}
    password: ${LOCAL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  springdoc:
    cache:
      disabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    secret: ${JWT_SECRET_KEY}

security:
  kakao:
    client_id: ${REST_API_KEY}
    redirect_uri: http://pposiraun.com/api/auth/kakao/callback
